const AuditActions = {
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
  PRODUCT_RESTORED: "PRODUCT_RESTORED",
  PRODUCT_ACTIVATED: "PRODUCT_ACTIVATED",
  PRODUCT_DEACTIVATED: "PRODUCT_DEACTIVATED",
  PRODUCT_PRICE_CHANGED: "PRODUCT_PRICE_CHANGED",
  PRODUCT_DETAILS_CHANGED: "PRODUCT_DETAILS_CHANGED",

  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_ARCHIVED: "CLIENT_ARCHIVED",
  CLIENT_RESTORED: "CLIENT_RESTORED",

  VENDOR_CREATED: "VENDOR_CREATED",
  VENDOR_UPDATED: "VENDOR_UPDATED",
  VENDOR_ARCHIVED: "VENDOR_ARCHIVED",
  VENDOR_RESTORED: "VENDOR_RESTORED",

  WORKER_CREATED: "WORKER_CREATED",
  WORKER_UPDATED: "WORKER_UPDATED",
  WORKER_ARCHIVED: "WORKER_ARCHIVED",
  WORKER_RESTORED: "WORKER_RESTORED",
  WORKER_SALARY_ADJUSTED: "WORKER_SALARY_ADJUSTED",

  INVENTORY_MOVEMENT_CREATED: "INVENTORY_MOVEMENT_CREATED",

  IMMUTABLE_RECORD_MODIFIED: "IMMUTABLE_RECORD_MODIFIED",

  TRANSACTION_POSTED: "TRANSACTION_POSTED",
  TRANSACTION_REVERSED: "TRANSACTION_REVERSED",

  MANUAL_STOCK_ADJUSTMENT: "MANUAL_STOCK_ADJUSTMENT",

  USER_CREATED: "USER_CREATED",
  USER_ARCHIVED: "USER_ARCHIVED",
  USER_RESTORED: "USER_RESTORED",
  ROLE_CHANGED: "ROLE_CHANGED",
};
module.exports = { AuditActions };
