const AuditActions = {
  // Products
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
  PRODUCT_RESTORED: "PRODUCT_RESTORED",
  PRODUCT_ACTIVATED: "PRODUCT_ACTIVATED",
  PRODUCT_DEACTIVATED: "PRODUCT_DEACTIVATED",
  PRODUCT_PRICE_CHANGED: "PRODUCT_PRICE_CHANGED",
  PRODUCT_DETAILS_CHANGED: "PRODUCT_DETAILS_CHANGED",

  // Materials
  MATERIAL_CREATED: "MATERIAL_CREATED",
  MATERIAL_ARCHIVED: "MATERIAL_ARCHIVED",
  MATERIAL_RESTORED: "MATERIAL_RESTORED",
  MATERIAL_MOVEMENT_CREATED: "MATERIAL_MOVEMENT_CREATED",

  // Inventory
  INVENTORY_MOVEMENT_CREATED: "INVENTORY_MOVEMENT_CREATED",

  // Purchase Orders
  PURCHASE_ORDER_RECEIVED: "PURCHASE_ORDER_RECEIVED",
  PURCHASE_ORDER_RETURNED: "PURCHASE_ORDER_RETURNED",
  PURCHASE_ORDER_CANCELLED: "PURCHASE_ORDER_CANCELLED",

  // Clients
  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_ARCHIVED: "CLIENT_ARCHIVED",
  CLIENT_RESTORED: "CLIENT_RESTORED",

  // Vendors
  VENDOR_CREATED: "VENDOR_CREATED",
  VENDOR_UPDATED: "VENDOR_UPDATED",
  VENDOR_ARCHIVED: "VENDOR_ARCHIVED",
  VENDOR_RESTORED: "VENDOR_RESTORED",

  // Workers
  WORKER_CREATED: "WORKER_CREATED",
  WORKER_UPDATED: "WORKER_UPDATED",
  WORKER_ARCHIVED: "WORKER_ARCHIVED",
  WORKER_RESTORED: "WORKER_RESTORED",
  WORKER_SALARY_ADJUSTED: "WORKER_SALARY_ADJUSTED",

  // Transactions
  TRANSACTION_POSTED: "TRANSACTION_POSTED",
  TRANSACTION_REVERSED: "TRANSACTION_REVERSED",

  // Stock
  MANUAL_STOCK_ADJUSTMENT: "MANUAL_STOCK_ADJUSTMENT",
  IMMUTABLE_RECORD_MODIFIED: "IMMUTABLE_RECORD_MODIFIED",

  // Users
  USER_CREATED: "USER_CREATED",
  USER_ARCHIVED: "USER_ARCHIVED",
  USER_RESTORED: "USER_RESTORED",
  ROLE_CHANGED: "ROLE_CHANGED",
};

module.exports = { AuditActions };
